### ISSUE TITLE
./simcommsys.master-omp-mpi-gmp.release -e localhost:local   why erros?  

### ISSUE THREAD

**Issue by Jirayuwujian** [jbresearch/simcommsys#1]
./simcommsys.master-omp-mpi-gmp.release -e localhost:local  why errors?
./simcommsys-batch.sh master-omp-mpi-gmp local "$settings" /home/jianwu/simcommsys/Examples/TemplateFolder/Systems   the usage is right?

**Comment by Jirayuwujian** [comment]
thank you very much!

**Comment by jabriffa** [comment]
Hi, can you explain a little what you're trying to achieve?

**Comment by Jirayuwujian** [comment]
Hi, thanks for your kindness , I want to run the simulation in the way of WiKi, it is pity that I failed.
simcommsys-batch.sh <tag> <port> <other> [<systems>] I cannot understand this command, how can I get this "port", and [<system>] means what, where should I run, I set these parameters, but it does not build the link, can you help me explain it? I start on Linux.

**Comment by Jirayuwujian** [comment]
simcommsys-batch.sh    <tag> <port> <other> [<systems>] ?

**Comment by Jirayuwujian** [comment]
simcommsys-batch.sh <tag> <port> <other> [<systems>]?`

**Comment by jabriffa** [comment]
I assume you managed to build and install the executables. The shell script that you mention is simply a convenience script to start multiple simulation servers; client instances can then be started to connect with this. You don't _have_ to use this script. You can, instead, simply use the simcommsys.tag.release executable directly. Either way, the port is the TCP/IP port on which the server listens. If you're not familiar with this term, I suggest you start by reading up on UNIX-type system use, etc. For the purposes of simcommsys, you can simply pick a port number to use that is greater than 1024. For example, 9999.

Alternatively, if you don't want to use the server/client architecture of simcommsys, and just want to start a simulation locally, you can use "local" instead of the port. In that case, though, do _not_ specify a hostname (i.e. just use 'local' not 'localhost:local').

I hope this helps. I will close this issue as it's not really a bug in the code. For general support with using simcommsys, please create a new discussion in the user forum (link on the first page of the wiki).
